### ISSUE TITLE
Deb, RPM and OSX installers of the Conjur CLI for v5 are available

### ISSUE THREAD

**Issue by kgilpin** [cyberark/conjur-cli#176]
Unlike the CLI for v4, I propose that the installers for v5 do not necessarily use the "omnibus" approach which bundles an entire Ruby VM with the installer. 

On recent Debian + Ubuntu, it is apparently now straightforward to install ruby from `apt`. Therefore, the `conjur-cli` package can depend on the `ruby` package. 

We should determine if the same is true for RPM and OSX. 

We should also evaluate if a homebrew recipe might be a better approach than a `dmg` installer for OSX.

**Comment by sgnn7** [comment]
Closing as invalid - Conjur CLI currently depends heavily on specific Ruby base version and they vary depending on the base OS. Appropriate approach to this will probably be a change to an alternative non-ruby single-binary implementation of the CLI.
