### ISSUE TITLE
Docker container build has been updated to work within CI pipeline

### ISSUE THREAD

**Issue by jtuttle** [cyberark/conjur-cli#195]
The cyberark/cli5 container is currently being built with Dockerfile.standalone. We instead want to work this into the CI pipeline. It should be tagged and pushed as `cyberark/conjur-cli:<version>`.

**Comment by izgeri** [comment]
this image is available in dockerhub [here](https://hub.docker.com/r/cyberark/conjur-cli/tags) - closing this issue
