### ISSUE TITLE
Code coverage is available in the CodeClimate for the Conjur CLI project

### ISSUE THREAD

**Issue by jvanderhoof** [cyberark/conjur-cli#248]
In order to better understand how robust our test coverage is for the Conjur API Gem, we need the following:
- [x] Code coverage is available in Jenkins <sup>1</sup>
- [ ] Code coverage is visible in CodeClimate repo page

<sup>1</sup> Ruby example: https://jenkins.conjur.net/job/cyberark--conjur/job/master/935/Coverage_20Report/

**Comment by jvanderhoof** [comment]
https://jenkins.conjur.net/job/cyberark--conjur-cli/job/master/Coverage_20Report/

**Comment by micahlee** [comment]
@jvanderhoof it looks like this is complete, is there something else to this issue?

![image](https://user-images.githubusercontent.com/1534633/74053725-6706fa80-49aa-11ea-8849-4a86bbe7f55a.png)
