### ISSUE TITLE
CLI image is overwritten on every master commit

### ISSUE THREAD

**Issue by izgeri** [cyberark/conjur-cli#270]
## Summary
At current, the Docker image for the CLI publishes to DockerHub every time a new code change
lands on master, overwriting the previous image with the same tag:
https://github.com/cyberark/conjur-cli/blob/dd2ced42ea912c26646a2377b8b2783a1165bcf9/Jenkinsfile#L96-L104

This needs to be updated to only publish new images to master when the commit matches a tag. This is already happening in many other repositories, but here is one example:
https://github.com/cyberark/secretless-broker/blob/8c7beec14fb952200dd6cb0792967865f3d89fc8/bin/publish#L36. 

## Expected Results
Only publish new image to DockerHub when the master commit matches a git tag.

## Actual Results (including error logs, if applicable)
Every commit that lands on master results in a new image for the VERSION being published to DockerHub.

**Comment by JakeQuilty** [comment]
I plan on just copying the `build_utils` script from Secretless to `bin` in this repo. Then I just plan on converting the part of Secretless' `publish` script to work for this repo. I don't think there should be any issue in this conversion, because they both use similar versioning.

**Comment by JakeQuilty** [comment]
PR: https://github.com/cyberark/conjur-cli/issues/270
