### ISSUE TITLE
Spike - decide how to create a containerless version of the CLI

### ISSUE THREAD

**Issue by Tovli** [cyberark/conjur-cli#296]
As we need to provide a way for customers to run the cli without any container runtime at all, we need to decide which CLI we want to use.
Currently we have a conjur-cli-go and conjur-cli and we need to decide which will be supported on VM

DoD:
- [ ] There is a document with the decision results
- [ ] We understand the main path we want to take to create a containerless cli

#### Security
Needs to be looked over by security architect

#### Time estimation

Go CLI: https://github.com/cyberark/conjur-cli-go#usage
Ruby CLI: https://github.com/cyberark/conjur-cli#commands
Python CLI: https://github.com/cyberark/conjur-api-python3/releases/tag/v0.0.5

**Comment by izgeri** [comment]
Should the Python CLI also be referenced here? https://github.com/cyberark/conjur-api-python3/releases/tag/v0.0.5

**Comment by sigalsax** [comment]
@izgeri yes most definitely. Added now
