### ISSUE TITLE
Update CLI to consume new Ruby client version

### ISSUE THREAD

**Issue by izgeri** [cyberark/conjur-cli#297]
Following the release of Conjur v1.9.0 (DAP 11.7+) which included a [medium security bug fix](https://github.com/cyberark/conjur/security/advisories/GHSA-qhjf-g9gm-64jq), the methods for API key rotation need to be updated to ensure they follow the new guidelines.

In cyberark/conjur-api-ruby#182, we release a new version of the Ruby client that includes an update related to this change - in this issue, we must update the CLI to use the newest Ruby client version to ensure the API key rotation functionality in the CLI works as expected with newer versions of Conjur / DAP.

**Comment by izgeri** [comment]
@sgnn7 I think this can be closed, but can you please confirm and add more details? if this can be closed, maybe we can close #298 too

**Comment by sgnn7** [comment]
Closing via findings documented [here](https://github.com/cyberark/conjur-cli/issues/298#issuecomment-716829963)
